### ISSUE TITLE
`Hi rai?` doesn't parse

### ISSUE THREAD

**Issue by eaburns** [eaburns/toaq#5]
Grammatically, `hi` is quantifier. This means that it cannot appear before anything besides predicate arguments. So, `hi rai?`, `hi rai~`, and `hi rai\ ho/` are all parse errors. I think that `hi` was intended to be allowed in all of these places, so it can be used as a general question-making word. However, this needs to be verified.

**Comment by este-rs** [comment]
Dupe of #14.
