### ISSUE TITLE
Test parsing of all dictionary words

### ISSUE THREAD

**Issue by eaburns** [eaburns/toaq#6]
As a sanity check, it would be good to have a script that can fetch the current dictionary and dump all of the words into a `[]string`, then add a test to verify that each successfully parses as just a single word.

**Comment by este-rs** [comment]
This isn't a good idea IMHO. Toadūa entries are quite the messy kind and parsing won't do them any good. If content restrictions are added to Toadūa one day, make sure to reopen.

**Comment by eaburns** [comment]
Ah. I was just referring to toaq.org/dictionary. I don't think Toadua exited when I opened this issue.

 My goal here was to make sure the parser wasn't missing any valid syllables and didn't have any strange bugs due to syllable combinations or some such.

Anyway, I'm not oppossed to closing it if we are confident enough that the word parsing is correct, given that the parser has been better exercised now.

**Comment by este-rs** [comment]
Aha, I think I see now. But since the list of valid rimes is standardised and publicly available, there's no room for mistake.

**Comment by eaburns** [comment]
Tell that to past me who had missed some:
https://github.com/eaburns/toaq/commit/f824935b7fa1c10d0c26ebec9684fa2e150110e3
https://github.com/eaburns/toaq/commit/f9fbbf2bef5bd4e1240e921bfa4d32dfa9e7d23d

Though to be fair, maybe one of those was new.

**Comment by este-rs** [comment]
Your past you didn't have access to the Discord `!endings` command. Our current us does.
